FROM mcr.microsoft.com/devcontainers/universal:2-linux
# Install the xz-utils package
RUN apt-get update && \
    npm install -g @vue/cli && \
    pip install flask

# READ ME!!!
# IF COMMAND NOT FOUND DO THIS: 
# Install Vue CLI using npm in bash command run this:
#   npm install -g @vue/cli
# Use pip to install Flask using bash command run this:
#   pip install flask
